LOCATION = "HZG"
SITE_PREFIX = "P??"
PATH_GPFS = "/asap3/petra3/gpfs/{}/{}/data/{}/processed/"
PATH_GPFS_EXTERNAL = "/asap3/petra3/gpfs/external/{}/data/{}/processed/"
DATASET_NAME_PATTERN = "{}/{}/{}/{}"
FILENAME_IGNORE_PATTERN = ["_ref", "_dar"]
LOG_SUFFIX = None
POSTPROCESSING = "reco"
SITE_PREFIX_HISTO = "HZG"
KEYWORDS = []
IMAGES_FULL = "images_full"
IMAGES = "images"
LABELS = "labels"