LOCATION = "HZG"
SITE_PREFIX = "P??"
PATH_GPFS = "/asap3/petra3/gpfs/{}/{}/data/{}/processed/Histology_Comparison_Registration/MgBone"
DATASET_NAME_PATTERN = "{}/{}/{}/{}"
FILENAME_IGNORE_PATTERN = ["_ref", "_dar"]
POSTPROCESSING = "reco"
SITE_PREFIX_HISTO = "HZG"
HISTO_RAW_DIRECTORY = "Histology_Microscopy"
LOG_SUFFIX = ".tif_meta.xml"
DATASET_NAME_DERIVED_SUFFIX = "histo-registered"
KEYWORDS = ["histology"]
KEYWORDS_DERIVED = ["registered", "stitched"]