CONFIG_LOCATION = "location"
CONFIG_PREFIX = "site_prefix"
CONFIG_SOURCE_PATH = "path_source"
CONFIG_LOG_FILENAMES = "meta_log_filenmaes"
CONFIG_LOG_SUFFIX = "scan_log_suffix"
CONFIG_KEYWORDS = "keywords"
CONFIG_DATASET_NAME = "dataset_name"
CONFIG_FILENAME_IGNORE = "filename_ignore"