LOCATION = "MHH/ZTL"
SITE_PREFIX = "MHH-ZTL"
SOURCE_PATH = "/nfs/fs/hzg/mdlma/data/MHH-ZTL/"
PATH_MR = "MR"
PATH_CT = "CT"
DAY_POST_SACRIFICE = "PS"
LOG_FILENAMES = []
LOG_SUFFIX = ".log"
KEYWORDS = ["rodent", "tomography", "longitudinal", "in-vivo"]  # Default keywords always added to any dataset beside other keywords
DATASET_MR_NAME_PATTERN = "{}/{}/{}/{}/{}"
DATASET_CT_NAME_PATTERN = "{}/{}/{}/{}/{}"
FILENAME_IGNORE_PATTERN = ["_ref", "_dar"]
DICOM_TAGS_MR = ["ImageType", "StudyDate", "Modality", "Manufacturer", "InstitutionName", "SeriesDescription", "ManufacturerModelName", "PatientName", "PatientID", "PatientSpeciesDescription", "ResponsibleOrganization", "ScanningSequence", "SequenceVariant", "ScanOptions", "MRAcquisitionType", "SequenceName", "SliceThickness", "RepetitionTime", "EchoTime", "MagneticFieldStrength", "SpacingBetweenSlices", "NumberOfPhaseEncodingSteps", "ProtocolName", "AcquisitionMatrix", "FlipAngle", "PatientPosition", "ImagePositionPatient", "ImageOrientationPatient", "ImagesInAcquisition", "PhotometricInterpretation", "Rows", "Columns", "PixelSpacing", "BitsAllocated", "BitsStored"]
DICOM_TAGS_CT = ["ImageType", "StudyDate", "Modality", "Manufacturer", "InstitutionName", "SeriesDescription", "ManufacturerModelName", "PatientName", "PatientID", "ScanOptions", "SliceThickness", "PatientPosition", "ImagePositionPatient", "ImageOrientationPatient", "ImagesInAcquisition", "PhotometricInterpretation", "Rows", "Columns", "PixelSpacing", "BitsAllocated", "BitsStored"]
PROPOSAL_ABSTRACT = "From: Medizinische Hochschule Hannover (MHH), Institut für Versuchstierkunde und Zentrales Tierlaboratorium (ZTL), AG Kleintierbildgebung (Martin Meier); In-vivo experiments monitoring the functional changes of tissue parameters during degradation process; Intercondylar in the knee (femur of rat); Implantation of biodegradable material: 8 animals MgCa; 7 in-vivo observations: Before implant (BL), 0d after implant, 3d after, 7d after, 14d after, 28d after, 56d after, and 72d after (before sacrifice); MR experiments: Bruker Pharmascan 7T and volume coil in S1 specified Lab conditions"
PROPOSAL_TITLE = "MHH-ZTL Rat Femur MgCa"
PROPOSAL_ID = "2017-ZTL-MgCa"
PROPOSAL_START = "2017-01-01"
PROPOSAL_END = "2017-12-31"
